In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
transactions = pd.read_csv("../data/raw/transactions.csv")
products = pd.read_csv("../data/raw/products.csv")
stores = pd.read_csv("../data/raw/stores.csv")
inventory = pd.read_csv("../data/raw/inventory.csv")
external_factors = pd.read_csv("../data/raw/external_factors.csv")

In [3]:
print("Transactions:", transactions.shape)
print("Products:", products.shape)
print("Stores:", stores.shape)
print("Inventory:", inventory.shape)
print("External Factors:", external_factors.shape)

Transactions: (76000, 9)
Products: (20, 4)
Stores: (5, 2)
Inventory: (76000, 5)
External Factors: (3800, 5)

In [4]:
print("TRANSACTIONS")
display(transactions.head())

print("PRODUCTS")
display(products.head())

print("STORES")
display(stores.head())

print("INVENTORY")
display(inventory.head())

print("EXTERNAL FACTORS")
display(external_factors.head())

TRANSACTIONS

,Date,Store ID,Product ID,Units Sold,Demand,Price,Discount,Promotion,Competitor Pricing
0,2022-01-01,S001,P0001,102,115,72.72,5,0,85.73
1,2022-01-01,S001,P0002,117,229,80.16,15,1,92.02
2,2022-01-01,S001,P0003,114,157,62.94,10,1,60.08
3,2022-01-01,S001,P0004,45,52,87.63,10,0,85.19
4,2022-01-01,S001,P0005,65,59,54.41,0,0,51.63

PRODUCTS

,Product ID,Observed Categories,Category Counts,Category Consistent
0,P0001,Electronics; Groceries; Toys,Electronics:760; Groceries:2280; Toys:760,No
1,P0002,Clothing; Electronics; Groceries; Toys,Clothing:760; Electronics:760; Groceries:1520;...,No
2,P0003,Clothing; Electronics; Furniture; Groceries; Toys,Clothing:760; Electronics:760; Furniture:760; ...,No
3,P0004,Electronics; Groceries,Electronics:760; Groceries:3040,No
4,P0005,Clothing; Electronics; Groceries; Toys,Clothing:760; Electronics:760; Groceries:1520;...,No

STORES

  Store ID Region
0     S001  North
1     S002  South
2     S003   East
3     S004   West
4     S005  North

INVENTORY

         Date Store ID Product ID  Inventory Level  Units Ordered
0  2022-01-01     S001      P0001              195            252
1  2022-01-01     S001      P0002              117            249
2  2022-01-01     S001      P0003              247            612
3  2022-01-01     S001      P0004              139            102
4  2022-01-01     S001      P0005              152            271

EXTERNAL FACTORS

         Date Store ID Weather Condition Seasonality  Epidemic
0  2022-01-01     S001             Snowy      Winter         0
1  2022-01-01     S002            Cloudy      Winter         0
2  2022-01-01     S003             Sunny      Winter         0
3  2022-01-01     S004             Snowy      Winter         0
4  2022-01-01     S005             Snowy      Winter         0

In [5]:
datasets = {
    "transactions": transactions,
    "products": products,
    "stores": stores,
    "inventory": inventory,
    "external_factors": external_factors
}

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)

    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

============================================================
TRANSACTIONS
============================================================
Shape: (76000, 9)

Columns:
['Date', 'Store ID', 'Product ID', 'Units Sold', 'Demand', 'Price', 'Discount', 'Promotion', 'Competitor Pricing']

Data Types:
Date                   object
Store ID               object
Product ID             object
Units Sold              int64
Demand                  int64
Price                 float64
Discount                int64
Promotion               int64
Competitor Pricing    float64
dtype: object

============================================================
PRODUCTS
============================================================
Shape: (20, 4)

Columns:
['Product ID', 'Observed Categories', 'Category Counts', 'Category Consistent']

Data Types:
Product ID             object
Observed Categories    object
Category Counts        object
Category Consistent    object
dtype: object

============================================================
STORES
============================================================
Shape: (5, 2)

Columns:
['Store ID', 'Region']

Data Types:
Store ID    object
Region      object
dtype: object

============================================================
INVENTORY
============================================================
Shape: (76000, 5)

Columns:
['Date', 'Store ID', 'Product ID', 'Inventory Level', 'Units Ordered']

Data Types:
Date               object
Store ID           object
Product ID         object
Inventory Level     int64
Units Ordered       int64
dtype: object

============================================================
EXTERNAL_FACTORS
============================================================
Shape: (3800, 5)

Columns:
['Date', 'Store ID', 'Weather Condition', 'Seasonality', 'Epidemic']

Data Types:
Date                 object
Store ID             object
Weather Condition    object
Seasonality          object
Epidemic              int64
dtype: object

In [6]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(f"{name.upper()} - MISSING VALUES")
    print("=" * 60)

    missing = pd.DataFrame({
        "Missing_Count": df.isnull().sum(),
        "Missing_Percentage": (
            df.isnull().sum() / len(df) * 100
        ).round(2)
    })

    display(missing)

============================================================
TRANSACTIONS - MISSING VALUES
============================================================

                    Missing_Count  Missing_Percentage
Date                            0                 0.0
Store ID                        0                 0.0
Product ID                      0                 0.0
Units Sold                      0                 0.0
Demand                          0                 0.0
Price                           0                 0.0
Discount                        0                 0.0
Promotion                       0                 0.0
Competitor Pricing              0                 0.0

============================================================
PRODUCTS - MISSING VALUES
============================================================

                     Missing_Count  Missing_Percentage
Product ID                       0                 0.0
Observed Categories              0                 0.0
Category Counts                  0                 0.0
Category Consistent              0                 0.0

============================================================
STORES - MISSING VALUES
============================================================

          Missing_Count  Missing_Percentage
Store ID              0                 0.0
Region                0                 0.0

============================================================
INVENTORY - MISSING VALUES
============================================================

                 Missing_Count  Missing_Percentage
Date                         0                 0.0
Store ID                     0                 0.0
Product ID                   0                 0.0
Inventory Level              0                 0.0
Units Ordered                0                 0.0

============================================================
EXTERNAL_FACTORS - MISSING VALUES
============================================================

                   Missing_Count  Missing_Percentage
Date                           0                 0.0
Store ID                       0                 0.0
Weather Condition              0                 0.0
Seasonality                    0                 0.0
Epidemic                       0                 0.0

In [7]:
for name, df in datasets.items():

    duplicate_count = df.duplicated().sum()

    print(
        f"{name}: {duplicate_count} exact duplicate rows"
    )

transactions: 0 exact duplicate rows
products: 0 exact duplicate rows
stores: 0 exact duplicate rows
inventory: 0 exact duplicate rows
external_factors: 0 exact duplicate rows

In [8]:
print(
    "Transactions Date-Store-Product duplicates:",
    transactions.duplicated(
        subset=["Date", "Store ID", "Product ID"]
    ).sum()
)

print(
    "Inventory Date-Store-Product duplicates:",
    inventory.duplicated(
        subset=["Date", "Store ID", "Product ID"]
    ).sum()
)

print(
    "External Date-Store duplicates:",
    external_factors.duplicated(
        subset=["Date", "Store ID"]
    ).sum()
)

print(
    "Product ID duplicates:",
    products.duplicated(
        subset=["Product ID"]
    ).sum()
)

print(
    "Store ID duplicates:",
    stores.duplicated(
        subset=["Store ID"]
    ).sum()
)

Transactions Date-Store-Product duplicates: 0
Inventory Date-Store-Product duplicates: 0
External Date-Store duplicates: 0
Product ID duplicates: 0
Store ID duplicates: 0

In [9]:
transaction_numeric = [
    "Units Sold",
    "Demand",
    "Price",
    "Discount",
    "Promotion",
    "Competitor Pricing"
]

display(
    transactions[transaction_numeric]
    .describe()
    .T
)

,count,mean,std,min,25%,50%,75%,max
Units Sold,76000.0,88.827316,43.994525,0.00,58.0000,84.0,114.0000,426.00
Demand,76000.0,104.317158,46.964801,4.00,71.0000,100.0,133.0000,430.00
Price,76000.0,67.726028,39.377899,4.74,31.9975,64.5,95.8300,228.03
Discount,76000.0,9.087039,7.475781,0.00,5.0000,10.0,10.0000,25.00
Promotion,76000.0,0.328947,0.469834,0.00,0.0000,0.0,1.0000,1.00
Competitor Pricing,76000.0,69.454029,40.943818,4.29,32.6200,65.7,97.9325,261.22

In [10]:
display(
    inventory[
        ["Inventory Level", "Units Ordered"]
    ]
    .describe()
    .T
)

,count,mean,std,min,25%,50%,75%,max
Inventory Level,76000.0,301.062842,226.510161,0.0,136.0,227.0,408.0,2267.0
Units Ordered,76000.0,89.090645,162.404627,0.0,0.0,0.0,121.0,1616.0

In [11]:
quality_checks = {
    "Negative Units Sold":
        (transactions["Units Sold"] < 0).sum(),

    "Negative Demand":
        (transactions["Demand"] < 0).sum(),

    "Non-positive Price":
        (transactions["Price"] <= 0).sum(),

    "Invalid Discount":
        (
            (transactions["Discount"] < 0) |
            (transactions["Discount"] > 100)
        ).sum(),

    "Invalid Promotion":
        (~transactions["Promotion"].isin([0, 1])).sum(),

    "Negative Inventory":
        (inventory["Inventory Level"] < 0).sum(),

    "Negative Units Ordered":
        (inventory["Units Ordered"] < 0).sum()
}

quality_checks_df = pd.DataFrame(
    quality_checks.items(),
    columns=["Quality Check", "Problem Rows"]
)

display(quality_checks_df)

            Quality Check  Problem Rows
0     Negative Units Sold             0
1         Negative Demand             0
2      Non-positive Price             0
3        Invalid Discount             0
4       Invalid Promotion             0
5      Negative Inventory             0
6  Negative Units Ordered             0

In [12]:
print("REGIONS")
display(stores["Region"].value_counts(dropna=False))

print("\nWEATHER CONDITIONS")
display(
    external_factors["Weather Condition"]
    .value_counts(dropna=False)
)

print("\nSEASONALITY")
display(
    external_factors["Seasonality"]
    .value_counts(dropna=False)
)

print("\nEPIDEMIC")
display(
    external_factors["Epidemic"]
    .value_counts(dropna=False)
)

print("\nPROMOTION")
display(
    transactions["Promotion"]
    .value_counts(dropna=False)
)

print("\nCATEGORY CONSISTENCY")
display(
    products["Category Consistent"]
    .value_counts(dropna=False)
)

REGIONS

Region
North    2
South    1
East     1
West     1
Name: count, dtype: int64

WEATHER CONDITIONS

Weather Condition
Cloudy    1218
Sunny     1149
Rainy      875
Snowy      558
Name: count, dtype: int64

SEASONALITY

Seasonality
Winter    1050
Spring     920
Summer     920
Autumn     910
Name: count, dtype: int64

EPIDEMIC

Epidemic
0    3040
1     760
Name: count, dtype: int64

PROMOTION

Promotion
0    51000
1    25000
Name: count, dtype: int64

CATEGORY CONSISTENCY

Category Consistent
No    20
Name: count, dtype: int64

In [13]:
transactions["Date"] = pd.to_datetime(
    transactions["Date"],
    errors="coerce"
)

inventory["Date"] = pd.to_datetime(
    inventory["Date"],
    errors="coerce"
)

external_factors["Date"] = pd.to_datetime(
    external_factors["Date"],
    errors="coerce"
)

In [14]:
print(
    "Transactions:",
    transactions["Date"].min(),
    "to",
    transactions["Date"].max()
)

print(
    "Inventory:",
    inventory["Date"].min(),
    "to",
    inventory["Date"].max()
)

print(
    "External Factors:",
    external_factors["Date"].min(),
    "to",
    external_factors["Date"].max()
)

Transactions: 2022-01-01 00:00:00 to 2024-01-30 00:00:00
Inventory: 2022-01-01 00:00:00 to 2024-01-30 00:00:00
External Factors: 2022-01-01 00:00:00 to 2024-01-30 00:00:00

In [15]:
print(
    "Invalid transaction dates:",
    transactions["Date"].isna().sum()
)

print(
    "Invalid inventory dates:",
    inventory["Date"].isna().sum()
)

print(
    "Invalid external factor dates:",
    external_factors["Date"].isna().sum()
)

Invalid transaction dates: 0
Invalid inventory dates: 0
Invalid external factor dates: 0

In [16]:
print("UNIQUE STORES")
print("Transactions:", transactions["Store ID"].nunique())
print("Stores:", stores["Store ID"].nunique())
print("Inventory:", inventory["Store ID"].nunique())
print("External Factors:", external_factors["Store ID"].nunique())

print("\nUNIQUE PRODUCTS")
print("Transactions:", transactions["Product ID"].nunique())
print("Products:", products["Product ID"].nunique())
print("Inventory:", inventory["Product ID"].nunique())

UNIQUE STORES
Transactions: 5
Stores: 5
Inventory: 5
External Factors: 5

UNIQUE PRODUCTS
Transactions: 20
Products: 20
Inventory: 20

In [17]:
transaction_products = set(transactions["Product ID"])
product_master = set(products["Product ID"])

print(
    "Products in transactions but missing from products.csv:",
    transaction_products - product_master
)

transaction_stores = set(transactions["Store ID"])
store_master = set(stores["Store ID"])

print(
    "Stores in transactions but missing from stores.csv:",
    transaction_stores - store_master
)

Products in transactions but missing from products.csv: set()
Stores in transactions but missing from stores.csv: set()